language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6.1
      env:
        - CXX=g++-6.1
        - CC=gcc-6.1
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8.1
          packages:
            - clang-3.8.1
      env:
        - CXX=clang++-3.8.1
        - CC=clang-3.8.1

script:
  - mkdir build && cd build && cmake ../
  - make
  - ctest
